# Generated by Django 5.2.14 on 2026-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0018_archivedlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettoraccount',
            name='multiplier',
            field=models.IntegerField(default=80),
        ),
    ]
