# Generated by Django 5.2.14 on 2026-09-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0019_bettoraccount_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCenterAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=150)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Control Center Audit',
                'verbose_name_plural': 'Control Center Audit',
                'ordering': ['-id'],
            },
        ),
    ]
